# 0 Preprocesamieento

librerias

In [ ]:
# Librerías base
import pandas as pd
import numpy as np
import pickle

# Visualización
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab

# Preprocesado
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

# Métricas
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [ ]:
#Estadistica Descriptiva
pylab.rcParams["figure.figsize"] = (14, 8)  # Tamaño por defecto de los gráficos

df = pd.read_csv("bd_onchain_final_with_tokenscout_coingecko.csv", dtype=str)


print("Info:") #info
df.info()

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5029 entries, 0 to 5028
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   address                    5029 non-null   object
 1   symbol                     5029 non-null   object
 2   name_x                     5029 non-null   object
 3   num_transfers              5029 non-null   object
 4   approx_holders             5029 non-null   object
 5   first_seen                 5029 non-null   object
 6   last_seen                  5029 non-null   object
 7   top10_concentration_proxy  5029 non-null   object
 8   avg_transfers_per_day      5029 non-null   object
 9   std_transfers_per_day      4571 non-null   object
 10  active_days                5029 non-null   object
 11  age_days                   5029 non-null   object
 12  inactive_days_proxy        5029 non-null   object
 13  organization               5029 non-null   object
 14  t1-labels                  5029 non-null   object
 15  t2-labels                  5029 non-null   object
 16  id                         5029 non-null   object
 17  name_y                     53 non-null     object
 18  current_price              5029 non-null   object
 19  market_cap                 5029 non-null   object
 20  total_volume               5029 non-null   object
dtypes: object(21)
memory usage: 825.2+ KB

In [ ]:
# === 1Resumen general ===
summary = pd.DataFrame({
    "Tipo": df.dtypes,
    "Nulos (#)": df.isna().sum(),
    "Nulos (%)": df.isna().mean() * 100,
    "Valores únicos": df.nunique(),
    "Únicos (%)": df.nunique() / len(df) * 100,
})

# Ordenar por % de nulos para revisar calidad
summary = summary.sort_values("Nulos (%)", ascending=False)

print("Resumen general de columnas:")
display(summary)

# === Top problemáticas ===
print("\n Top 10 columnas con más NaN:")
display(summary.head(10))

print("\n Top 10 columnas con más valores únicos:")
display(summary.sort_values("Únicos (%)", ascending=False).head(10))

# === 3Ejemplo de categorías más frecuentes ===
cat_cols = df.select_dtypes(include="object").columns
print("\nEjemplos de distribuciones categóricas:")
for col in cat_cols[:5]:  # mostramos solo las primeras 5 por brevedad
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(5))

Resumen general de columnas:

,Tipo,Nulos (#),Nulos (%),Valores únicos,Únicos (%)
name_y,object,4976,98.946113,47,0.934579
std_transfers_per_day,object,458,9.107178,3890,77.351362
name_x,object,0,0.000000,4829,96.023066
symbol,object,0,0.000000,4323,85.961424
address,object,0,0.000000,5000,99.423345
approx_holders,object,0,0.000000,1414,28.116922
num_transfers,object,0,0.000000,1655,32.909127
top10_concentration_proxy,object,0,0.000000,4968,98.787035
first_seen,object,0,0.000000,4993,99.284152
avg_transfers_per_day,object,0,0.000000,3179,63.213362
active_days,object,0,0.000000,569,11.314377
age_days,object,0,0.000000,1683,33.465898
last_seen,object,0,0.000000,4945,98.329688
inactive_days_proxy,object,0,0.000000,1550,30.821237
organization,object,0,0.000000,2,0.039769
t2-labels,object,0,0.000000,5,0.099423
t1-labels,object,0,0.000000,3,0.059654
id,object,0,0.000000,49,0.974349
current_price,object,0,0.000000,49,0.974349
market_cap,object,0,0.000000,39,0.775502
total_volume,object,0,0.000000,49,0.974349

 Top 10 columnas con más NaN:

,Tipo,Nulos (#),Nulos (%),Valores únicos,Únicos (%)
name_y,object,4976,98.946113,47,0.934579
std_transfers_per_day,object,458,9.107178,3890,77.351362
name_x,object,0,0.000000,4829,96.023066
symbol,object,0,0.000000,4323,85.961424
address,object,0,0.000000,5000,99.423345
approx_holders,object,0,0.000000,1414,28.116922
num_transfers,object,0,0.000000,1655,32.909127
top10_concentration_proxy,object,0,0.000000,4968,98.787035
first_seen,object,0,0.000000,4993,99.284152
avg_transfers_per_day,object,0,0.000000,3179,63.213362

 Top 10 columnas con más valores únicos:

,Tipo,Nulos (#),Nulos (%),Valores únicos,Únicos (%)
address,object,0,0.000000,5000,99.423345
first_seen,object,0,0.000000,4993,99.284152
top10_concentration_proxy,object,0,0.000000,4968,98.787035
last_seen,object,0,0.000000,4945,98.329688
name_x,object,0,0.000000,4829,96.023066
symbol,object,0,0.000000,4323,85.961424
std_transfers_per_day,object,458,9.107178,3890,77.351362
avg_transfers_per_day,object,0,0.000000,3179,63.213362
age_days,object,0,0.000000,1683,33.465898
num_transfers,object,0,0.000000,1655,32.909127

Ejemplos de distribuciones categóricas:

--- address ---
address
0x7248fcf715c8016a18bb3f916e310c698e355e45    11
0x83c5c28494df3af44b6ac614e0acb3a64f399b20     5
0x4bd2fd4b48f2ac589bfd2b345e51a488a604ba59     4
0xa7b940d0e0a4f03cf9913a558597360c34adef2e     3
0x458f9dac05af6f2d32263272438650254ffb40d9     2
Name: count, dtype: int64

--- symbol ---
symbol
USDT      32
VSHARE    21
HT        18
ETH       15
USDC      14
Name: count, dtype: int64

--- name_x ---
name_x
Tether USD             22
Virtual Augur Share    21
gm frens               11
HuobiToken             11
USD Coin               11
Name: count, dtype: int64

--- num_transfers ---
num_transfers
10    181
11    160
14    120
12    119
13    112
Name: count, dtype: int64

--- approx_holders ---
approx_holders
14    140
15    134
13    131
12    121
10    113
Name: count, dtype: int64

## 0-1 Eliminación de columnas irrelevantes
Variables con demasiados nulos (>90%)

name_y → 98% nulos → se elimina porque no aporta información confiable.

Variables con valores casi únicos (>90%)

first_seen, last_seen (≈99% únicos) → casi identificadores temporales, difícil generalizar, se descartan.

name_x, id, symbol se descartan es más relevante el address es más especifico.

Variables categóricas con muy pocos valores únicos

organization (2 valores) e id (49 valores) → bajo poder predictivo, se descartan.

Variables financieras (current_price, market_cap, total_volume)

Aunque parecen importantes, muestran <1% de variabilidad en toda la muestra → no diferencian entre tokens → se descartan (probable error de merge o baja cobertura).

In [ ]:
# Copia del dataframe original
df_1 = df.copy()

# Columnas a eliminar según criterio justificado
drop_cols = [
    "name_y", "name_x", "symbol", "first_seen", "last_seen",
    "organization", "id", "current_price", "market_cap", "total_volume"
]

df_1 = df_1.drop(columns=drop_cols, errors="ignore")

# Convertir posibles numéricas que vienen como 'object'
num_cols = [
    "num_transfers", "approx_holders", "avg_transfers_per_day",
    "std_transfers_per_day", "active_days", "age_days",
    "inactive_days_proxy", "top10_concentration_proxy"
]
for col in num_cols:
    if col in df_1.columns:
        df_1[col] = pd.to_numeric(df_1[col], errors="coerce")

print("Preprocesamiento listo. Shape final:", df_1.shape)
print("Columnas finales:", df_1.columns.tolist())

Preprocesamiento listo. Shape final: (5029, 11)
Columnas finales: ['address', 'num_transfers', 'approx_holders', 'top10_concentration_proxy', 'avg_transfers_per_day', 'std_transfers_per_day', 'active_days', 'age_days', 'inactive_days_proxy', 't1-labels', 't2-labels']

## 0-2 Revisión de variables restantes

In [ ]:
# Candidatas tras limpieza inicial
cols_revisar = [
    "address", "approx_holders", "num_transfers",
    "std_transfers_per_day", "avg_transfers_per_day",
    "active_days", "age_days", "inactive_days_proxy",
    "top10_concentration_proxy", "t2-labels", "t1-labels"
]

df_check = df_1.copy()

#eliminar etiquetas faltantes
df_check = df_check[~((df_check["t1-labels"].astype(str) == "0") | (df_check["t2-labels"].astype(str) == "0"))]

# Intentar conversión de object a numérico (sin dañar categóricas claras)
num_like = [
    "approx_holders", "num_transfers", "std_transfers_per_day",
    "avg_transfers_per_day", "active_days", "age_days",
    "inactive_days_proxy", "top10_concentration_proxy"
]
for col in num_like:
    df_check[col] = pd.to_numeric(df_check[col], errors="coerce")

# Resumen detallado
def resumen_columnas(df):
    """
    Muestra un resumen de cada columna del DataFrame: tipo, % de NaN, cantidad de valores únicos
    y top 5 valores más frecuentes.
    """
    for col in df.columns:
        print(f"\n--- {col} ---")
        print(f"Tipo: {df[col].dtype}")
        print(f"% NaN: {df[col].isna().mean() * 100:.2f}")
        print(f"Valores únicos: {df[col].nunique()}")

        top_vals = df[col].value_counts(dropna=False).head(5)
        print("Top 5 valores más frecuentes:")
        print(top_vals.to_dict())
resumen_columnas(df_check)

--- address ---
Tipo: object
% NaN: 0.00
Valores únicos: 4712
Top 5 valores más frecuentes:
{'0x83c5c28494df3af44b6ac614e0acb3a64f399b20': 5, '0x4bd2fd4b48f2ac589bfd2b345e51a488a604ba59': 4, '0xa7b940d0e0a4f03cf9913a558597360c34adef2e': 3, '0x18b3367bef43a415ebcfa359e272112dd5b96709': 2, '0x0ad955d68acd3afa075610349265bcfa9f0cf0b6': 2}

--- num_transfers ---
Tipo: int64
% NaN: 0.00
Valores únicos: 1601
Top 5 valores más frecuentes:
{10: 170, 11: 151, 14: 115, 12: 113, 13: 109}

--- approx_holders ---
Tipo: int64
% NaN: 0.00
Valores únicos: 1370
Top 5 valores más frecuentes:
{14: 131, 15: 125, 13: 125, 12: 109, 10: 105}

--- top10_concentration_proxy ---
Tipo: float64
% NaN: 0.00
Valores únicos: 4680
Top 5 valores más frecuentes:
{100000000.0: 19, 1.0: 5, 155221760.35172415: 5, 1.8131761341389936e+21: 4, 14.0: 3}

--- avg_transfers_per_day ---
Tipo: float64
% NaN: 0.00
Valores únicos: 2987
Top 5 valores más frecuentes:
{2.0: 65, 10.0: 48, 2.5: 48, 3.0: 47, 5.0: 46}

--- std_transfers_per_day ---
Tipo: float64
% NaN: 7.44
Valores únicos: 3726
Top 5 valores más frecuentes:
{nan: 352, 5.656854249492381: 20, 6.363961030678928: 19, 0.7071067811865476: 16, 0.7867957924694432: 15}

--- active_days ---
Tipo: int64
% NaN: 0.00
Valores únicos: 567
Top 5 valores más frecuentes:
{1: 352, 2: 240, 3: 205, 5: 196, 4: 193}

--- age_days ---
Tipo: int64
% NaN: 0.00
Valores únicos: 1669
Top 5 valores más frecuentes:
{0: 450, 1: 63, 2: 40, 3: 36, 7: 33}

--- inactive_days_proxy ---
Tipo: int64
% NaN: 0.00
Valores únicos: 1543
Top 5 valores más frecuentes:
{-1: 436, -2: 139, 0: 55, 3: 46, 2: 38}

--- t1-labels ---
Tipo: object
% NaN: 0.00
Valores únicos: 2
Top 5 valores más frecuentes:
{'scam': 4559, 'truthworthy': 171}

--- t2-labels ---
Tipo: object
% NaN: 0.00
Valores únicos: 4
Top 5 valores más frecuentes:
{'rugpull': 3367, 'honeypot': 734, 'ponzi': 458, 'truthworthy': 171}

Variables categóricas
address Identificado, combinar datos repetidos.

Variables numéricas de actividad
num_transfers, approx_holders, avg_transfers_per_day, active_days, age_days: relevantes y deben conservarse.
std_transfers_per_day: se conserva, imputando ~9% de valores faltantes.
top10_concentration_proxy: importante pero con outliers extremos, requiere tratamiento.
inactive_days_proxy: tiene valores negativos que deben recodificarse.

Etiquetas
t1-labels: opción binaria (scam vs. trustworthy).
t2-labels: opción multiclase (rugpull, honeypot, ponzi, etc.).

## 0-3 0-4 Conversión de tipos y Tratamiento de valores faltantes

1.   Elemento de lista
2.   Elemento de lista

In [ ]:
df_3 = df_check.copy()


# Conversión de tipos
# -----------------------------
num_cols = ['num_transfers','approx_holders','top10_concentration_proxy',
            'avg_transfers_per_day','std_transfers_per_day',
            'active_days','age_days','inactive_days_proxy']

for col in num_cols:
    df_3[col] = pd.to_numeric(df_3[col], errors='coerce')  # fuerza numérico

cat_cols = ['address','t1-labels','t2-labels']
for col in cat_cols:
    df_3[col] = df_3[col].astype('category')

# -----------------------------
# 4Tratamiento de valores faltantes y valores inválidos
# -----------------------------

# std_transfers_per_day: NaN → 0
df_3['std_transfers_per_day'] = df_3['std_transfers_per_day'].fillna(0)

# approx_holders: si hay 0 → imputar con mediana
df_3['approx_holders'] = df_3['approx_holders'].replace(0, np.nan)
df_3['approx_holders'] = df_3['approx_holders'].fillna(df_3['approx_holders'].median())

# inactive_days_proxy: valores negativos → NaN, imputar con mediana
df_3['inactive_days_proxy'] = df_3['inactive_days_proxy'].apply(lambda x: x if x >= 0 else np.nan)
df_3['inactive_days_proxy'] = df_3['inactive_days_proxy'].fillna(df_3['inactive_days_proxy'].median())

# active_days: si aparece 0 → considerar NaN e imputar con mediana
df_3['active_days'] = df_3['active_days'].replace(0, np.nan)
df_3['active_days'] = df_3['active_days'].fillna(df_3['active_days'].median())

# top10_concentration_proxy: valores negativos → NaN e imputar con mediana
df_3['top10_concentration_proxy'] = df_3['top10_concentration_proxy'].apply(lambda x: x if x >= 0 else np.nan)
df_3['top10_concentration_proxy'] = df_3['top10_concentration_proxy'].fillna(df_3['top10_concentration_proxy'].median())


print(df_3.info())
print(df_3.head())

<class 'pandas.core.frame.DataFrame'>
Index: 4730 entries, 0 to 5028
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   address                    4730 non-null   category
 1   num_transfers              4730 non-null   int64
 2   approx_holders             4730 non-null   int64
 3   top10_concentration_proxy  4730 non-null   float64
 4   avg_transfers_per_day      4730 non-null   float64
 5   std_transfers_per_day      4730 non-null   float64
 6   active_days                4730 non-null   int64
 7   age_days                   4730 non-null   int64
 8   inactive_days_proxy        4730 non-null   float64
 9   t1-labels                  4730 non-null   category
 10  t2-labels                  4730 non-null   category
dtypes: category(3), float64(4), int64(4)
memory usage: 517.2 KB
None
                                      address  num_transfers  approx_holders  \
0  0x2a2c06306f1352b7e742bb09eb421f91ffa2791a            114              86
1  0x9b613bb970ef1f8dd15f9da863fe6b059c20dfb6             11              10
2  0x74004a7227615fb52b82d17ffabfa376907d8a4d             54              46
3  0x05271b76b10c785358f531281138e2b296821905             11               5
4  0x3c4bea627039f0b7e7d21e34bb9c9fe962977518          26616           22887

   top10_concentration_proxy  avg_transfers_per_day  std_transfers_per_day  \
0               9.112790e+24               2.850000               2.402456
1               1.482727e+24               1.571429               1.133893
2               1.386268e+24               1.350000               0.769615
3               1.480000e+10              11.000000               0.000000
4               1.686164e+23              25.666345             226.132817

   active_days  age_days  inactive_days_proxy    t1-labels    t2-labels
0           40       806                766.0         scam     honeypot
1            7        19                 12.0         scam      rugpull
2           40      1160               1120.0         scam      rugpull
3            1         0                321.0         scam     honeypot
4         1037      2780               1743.0  truthworthy  truthworthy

Primero quitamos columnas con >90% nulos, porque casi no aportan y

---

entorpecen imputación.

---



La conversión a numérico se hace solo si una alta fracción de valores se convierten correctamente (evita convertir symbol o address por error).

Las categóricas de baja cardinalidad se transforman a category (útil para codificación posterior y memoria).

Imputación: mediana para numéricas (robusta ante outliers), modo o "unknown" para categóricas según cardinalidad.

## 0-5 Codificación de variables categóricas

---

In [ ]:

df_5 = df_3.copy()

le_t1 = LabelEncoder()
df_5['t1-labels_encoded'] = le_t1.fit_transform(df_5['t1-labels'])

le_t2 = LabelEncoder()
df_5['t2-labels_encoded'] = le_t2.fit_transform(df_5['t2-labels'])

## 0-6 Detección y tratamiento de outliers

In [ ]:
df_6 = df_5.copy()

num_cols = df_6.select_dtypes(include='number').columns.tolist()
# Excluir columnas de labels codificadas
num_cols = [col for col in num_cols if col not in ['t1-labels_encoded', 't2-labels_encoded']]
print(df_6[num_cols].describe())

       num_transfers  approx_holders  top10_concentration_proxy  \
count   4.730000e+03    4.730000e+03               4.730000e+03
mean    9.589978e+03    3.962207e+03               3.558508e+73
std     1.464516e+05    3.411442e+04               1.335055e+75
min     1.000000e+01    2.000000e+00               0.000000e+00
25%     2.100000e+01    1.800000e+01               1.298810e+13
50%     8.000000e+01    5.300000e+01               1.275649e+22
75%     6.427500e+02    3.630000e+02               4.606339e+24
max     8.947724e+06    1.507632e+06               6.947525e+76

       avg_transfers_per_day  std_transfers_per_day  active_days     age_days  \
count            4730.000000            4730.000000  4730.000000  4730.000000
mean               45.416670             105.170570    95.441015   616.595349
std               457.390099             989.396763   269.627652   763.391311
min                 1.000000               0.000000     1.000000     0.000000
25%                 2.750000               1.744671     5.000000    43.000000
50%                 6.031025               5.748911    16.000000   277.500000
75%                19.165760              30.366955    64.000000   937.750000
max             19989.000000           55314.788885  3079.000000  3297.000000

       inactive_days_proxy
count          4730.000000
mean            560.327484
std             619.157062
min               0.000000
25%             101.000000
50%             321.000000
75%             810.000000
max            3047.000000

In [ ]:

# Tratar outliers usando percentiles 2 y 98
for col in num_cols:
    lower = df_6[col].quantile(0.02)    #se achico más de lo normal debido a gran cantidad de outlier
    upper = df_6[col].quantile(0.98)
    df_6[col + '_capped'] = df_6[col].clip(lower, upper)

# Aplicar log-transform a las variables sesgadas
log_cols = [
    'num_transfers_capped',
    'approx_holders_capped',
    'top10_concentration_proxy_capped',
    'avg_transfers_per_day_capped',
    'std_transfers_per_day_capped',
    'active_days_capped',
    'age_days_capped',
    'inactive_days_proxy_capped'
]

for col in log_cols:
    df_6[col + '_log'] = np.log1p(df_6[col])

# Resumen estadístico post-tratamiento
summary = df_6[[c + '_log' for c in log_cols]].describe().T
summary['skew'] = df_6[[c + '_log' for c in log_cols]].skew()
summary['kurtosis'] = df_6[[c + '_log' for c in log_cols]].kurtosis()

print(summary)

                                       count       mean        std       min  \
num_transfers_capped_log              4730.0   5.063165   2.337477  2.397895
approx_holders_capped_log             4730.0   4.674658   2.188120  1.945910
top10_concentration_proxy_capped_log  4730.0  43.553483  17.936011  2.418638
avg_transfers_per_day_capped_log      4730.0   2.293249   1.206981  0.830348
std_transfers_per_day_capped_log      4730.0   2.339748   1.730914  0.000000
active_days_capped_log                4730.0   3.069701   1.581653  0.693147
age_days_capped_log                   4730.0   5.004741   2.340282  0.000000
inactive_days_proxy_capped_log        4730.0   5.465876   1.640914  1.098612

                                            25%        50%        75%  \
num_transfers_capped_log               3.091042   4.394449   6.467310
approx_holders_capped_log              2.944439   3.988984   5.897154
top10_concentration_proxy_capped_log  30.195026  50.900326  56.789464
avg_transfers_per_day_capped_log       1.321756   1.950332   3.003985
std_transfers_per_day_capped_log       1.009661   1.909381   3.445753
active_days_capped_log                 1.791759   2.833213   4.174387
age_days_capped_log                    3.784190   5.629416   6.844549
inactive_days_proxy_capped_log         4.624973   5.774552   6.698268

                                            max      skew  kurtosis
num_transfers_capped_log              11.107529  0.903898 -0.114246
approx_holders_capped_log             10.568007  1.007300  0.173268
top10_concentration_proxy_capped_log  73.358857 -0.754344 -0.452650
avg_transfers_per_day_capped_log       5.637963  0.975641  0.243612
std_transfers_per_day_capped_log       6.750265  0.776980 -0.196918
active_days_capped_log                 6.795348  0.488395 -0.536086
age_days_capped_log                    7.902680 -0.876500 -0.252819
inactive_days_proxy_capped_log         7.718285 -0.900312  0.266803

\| Feature                            | Max   | Skew | Kurtosis | Observación                                                                                             |
| ---------------------------------- | ----- | ---- | -------- | ------------------------------------------------------------------------------------------------------- |
| `num_transfers_capped_log`         | 11.11 | 0.90 | -0.11    | Ligeramente sesgada a la derecha; capping y log ayudaron mucho.                                         |
| `approx_holders_capped_log`        | 10.57 | 1.01 | 0.17     | Sesgo positivo más marcado; todavía algunos valores relativamente altos dominan la media.               |
| `avg_transfers_per_day_capped_log` | 5.64  | 0.98 | 0.24     | Sesgo positivo; la mayoría de días con pocas transferencias, algunos días muy activos todavía influyen. |
| `std_transfers_per_day_capped_log` | 6.75  | 0.78 | -0.20    | Sesgo positivo moderado; valores extremos suavizados pero todavía algo dispersos.                       |

| Feature                                | Max   | Skew  | Kurtosis | Observación                                                                                       |
| -------------------------------------- | ----- | ----- | -------- | ------------------------------------------------------------------------------------------------- |
| `age_days_capped_log`                  | 7.90  | -0.88 | -0.25    | Sesgo negativo; la mayoría de los activos son recientes, pocos antiguos.                          |
| `inactive_days_proxy_capped_log`       | 7.72  | -0.90 | 0.27     | Sesgo negativo; muchos activos con pocos días inactivos, algunos con muchos.                      |
| `top10_concentration_proxy_capped_log` | 73.36 | -0.75 | -0.45    | Altamente dispersa; valores extremos siguen dominando la variable, aunque log y capping ayudaron. |

## 0-7 Escalado de variables numéricas

In [ ]:
df_7=df_6.copy()
scaler = MinMaxScaler(feature_range=(0,6))
num = [
    'num_transfers_capped_log', 'approx_holders_capped_log', 'top10_concentration_proxy_capped_log',
    'avg_transfers_per_day_capped_log', 'std_transfers_per_day_capped_log', 'active_days_capped_log',
    'age_days_capped_log', 'inactive_days_proxy_capped_log'
]
df_7[num] = scaler.fit_transform(df_7[num])
print(df_7[num].describe())

       num_transfers_capped_log  approx_holders_capped_log  \
count               4730.000000                4730.000000
mean                   1.836084                   1.898899
std                    1.610270                   1.522683
min                    0.000000                   0.000000
25%                    0.477504                   0.694863
50%                    1.375411                   1.421747
75%                    2.803389                   2.749617
max                    6.000000                   6.000000

       top10_concentration_proxy_capped_log  avg_transfers_per_day_capped_log  \
count                           4730.000000                       4730.000000
mean                               3.479113                          1.825730
std                                1.516997                          1.506337
min                                0.000000                          0.000000
25%                                2.349278                          0.613287
50%                                4.100497                          1.397763
75%                                4.598590                          2.712742
max                                6.000000                          6.000000

       std_transfers_per_day_capped_log  active_days_capped_log  \
count                       4730.000000             4730.000000
mean                           2.079694                2.336751
std                            1.538530                1.555163
min                            0.000000                0.000000
25%                            0.897441                1.080213
50%                            1.697161                2.104224
75%                            3.062771                3.422936
max                            6.000000                6.000000

       age_days_capped_log  inactive_days_proxy_capped_log
count          4730.000000                     4730.000000
mean              3.799781                        3.958441
std               1.776826                        1.487307
min               0.000000                        0.000000
25%               2.873094                        3.196255
50%               4.274056                        4.238221
75%               5.196629                        5.075467
max               6.000000                        6.000000

## 0-8 Guardado

In [ ]:
df_8=df_7.copy()
print("Columnas finales:", df_7.columns.tolist())

Columnas finales: ['address', 'num_transfers', 'approx_holders', 'top10_concentration_proxy', 'avg_transfers_per_day', 'std_transfers_per_day', 'active_days', 'age_days', 'inactive_days_proxy', 't1-labels', 't2-labels', 't1-labels_encoded', 't2-labels_encoded', 'num_transfers_capped', 'approx_holders_capped', 'top10_concentration_proxy_capped', 'avg_transfers_per_day_capped', 'std_transfers_per_day_capped', 'active_days_capped', 'age_days_capped', 'inactive_days_proxy_capped', 'num_transfers_capped_log', 'approx_holders_capped_log', 'top10_concentration_proxy_capped_log', 'avg_transfers_per_day_capped_log', 'std_transfers_per_day_capped_log', 'active_days_capped_log', 'age_days_capped_log', 'inactive_days_proxy_capped_log']

In [ ]:
# Columnas finales
final_cols = [
    'address',
    't1-labels_encoded', 't2-labels_encoded','t1-labels', 't2-labels',
    'num_transfers_capped_log', 'approx_holders_capped_log', 'top10_concentration_proxy_capped_log',
    'avg_transfers_per_day_capped_log', 'std_transfers_per_day_capped_log', 'active_days_capped_log',
    'age_days_capped_log', 'inactive_days_proxy_capped_log'
]

# Crear copia
df_8=df_7[final_cols].copy()

# Revisar la forma y primeras filas
print(df_8.shape)
print(df_8.head())

(4730, 13)
                                      address  t1-labels_encoded  \
0  0x2a2c06306f1352b7e742bb09eb421f91ffa2791a                  0
1  0x9b613bb970ef1f8dd15f9da863fe6b059c20dfb6                  0
2  0x74004a7227615fb52b82d17ffabfa376907d8a4d                  0
3  0x05271b76b10c785358f531281138e2b296821905                  0
4  0x3c4bea627039f0b7e7d21e34bb9c9fe962977518                  1

   t2-labels_encoded    t1-labels    t2-labels  num_transfers_capped_log  \
0                  0         scam     honeypot                  1.616856
1                  2         scam      rugpull                  0.059941
2                  2         scam      rugpull                  1.108729
3                  0         scam     honeypot                  0.059941
4                  3  truthworthy  truthworthy                  5.367443

   approx_holders_capped_log  top10_concentration_proxy_capped_log  \
0                   1.753632                              4.656294
1                   0.314530                              4.502717
2                   1.325133                              4.497028
3                   0.000000                              1.776080
4                   5.631432                              4.318843

   avg_transfers_per_day_capped_log  std_transfers_per_day_capped_log  \
0                          0.646131                          1.088400
1                          0.142416                          0.673705
2                          0.030036                          0.507324
3                          2.064922                          0.000000
4                          3.061461                          4.822509

   active_days_capped_log  age_days_capped_log  inactive_days_proxy_capped_log
0                2.969838             5.081813                        5.024908
1                1.363076             2.274468                        1.329072
2                2.969838             5.357957                        5.368873
3                0.000000             0.000000                        4.238221
4                6.000000             6.000000                        5.769461

In [ ]:
targets = ['t1-labels_encoded', 't2-labels_encoded']

for t in targets:
    print(f"--- {t} ---")
    print(df_8[t].value_counts())
    print(df_8[t].value_counts(normalize=True))
    print("\n")

--- t1-labels_encoded ---
t1-labels_encoded
0    4559
1     171
Name: count, dtype: int64
t1-labels_encoded
0    0.963848
1    0.036152
Name: proportion, dtype: float64


--- t2-labels_encoded ---
t2-labels_encoded
2    3367
0     734
1     458
3     171
Name: count, dtype: int64
t2-labels_encoded
2    0.711839
0    0.155180
1    0.096829
3    0.036152
Name: proportion, dtype: float64

In [ ]:
with open("df_preprocesado.pkl", "wb") as f:
    pickle.dump(df_8, f)

print(f"\nDataset generado con éxito con {len(df_8)} registros en formato .pkl")

Dataset generado con éxito con 4730 registros en formato .pkl